<?php

namespace Database\Seeders;

use App\Models\Branch;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing branches before seeding to prevent duplicates
        Branch::truncate();

        $branches = [
            [
                'name' => 'DANCELL POM (PUSAT WARUJAYENG)',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => NULL,
                'is_hq' => true,
                'address' => 'JL. A. YANI NO 19 WARUJAYENG, TANJUNGANOM, NGANJUK (SELATAN POM WARUJAYENG)',
                'phone' => '085230855400',
                'whatsapp' => '085230855400',
                'google_maps_url' => 'https://maps.google.com/?cid=2638569193056379776&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 1,
            ],
            [
                'name' => 'DANCELL SONGO',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. DR SOETOMO NO 11 BARAT PUSKESMAS WARUJAYENG (BARAT PUSKESMAS WARUJAYENG)',
                'phone' => '085706133225',
                'whatsapp' => '085706133225',
                'google_maps_url' => 'https://maps.google.com/?cid=2589396057596508451&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 2,
            ],
            [
                'name' => 'DANCELL GADING',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'DEPAN PASAR GADING PRAMBON NGANJUK',
                'phone' => '081440009806',
                'whatsapp' => '081440009806',
                'google_maps_url' => 'https://maps.google.com/?cid=890743784448476412&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 3,
            ],
            [
                'name' => 'DANCELL KERTOSONO',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. AHMAD YANI NO 83 KERTOSONO (DEPAN PONPES LDII)',
                'phone' => '085655858283',
                'whatsapp' => '085655858283',
                'google_maps_url' => 'https://maps.google.com/?cid=3527741409200004011&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 4,
            ],
            [
                'name' => 'DANCELL KOTA 1 (NYAWIJI)',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. A YANI NO 235 NGANJUK (DEPAN TAMAN NYAWIJI NGANJUK)',
                'phone' => '08133710500',
                'whatsapp' => '08133710500',
                'google_maps_url' => 'https://maps.google.com/?cid=13120694089330148747&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 5,
            ],
            [
                'name' => 'DANCELL PARE 1',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. PB SUDIRMAN NO 90 PARE (DEPAN ROCKET CHICKEN)',
                'phone' => '082229088989',
                'whatsapp' => '082229088989',
                'google_maps_url' => 'https://maps.google.com/?cid=8466836405475426107&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 6,
            ],
            [
                'name' => 'DANCELL D\'ROOFTOP',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. JENDRAL A.YANI NO 81 (DEPAN KANTOR KECAMATAN TANJUNGANOM NGANJUK)',
                'phone' => '081232720989',
                'whatsapp' => '081232720989',
                'google_maps_url' => 'https://maps.google.com/?cid=1354159210040300463&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 7,
            ],
            [
                'name' => 'DANCELL PARE 2',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. A.YANI NO 36 PARE-KEDIRI (DEPAN TOKO ALAT TULIS REMAJA)',
                'phone' => '082136719998',
                'whatsapp' => '082136719998',
                'google_maps_url' => 'https://maps.google.com/?cid=17620194480111997889&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 8,
            ],
            [
                'name' => 'DANCELL KOTA 2 (PLOSO)',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. A YANI NO 354 PLOSO, NGANJUK',
                'phone' => '081232704607',
                'whatsapp' => '081232704607',
                'google_maps_url' => 'https://maps.google.com/?cid=8019881850249767280&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 9,
            ],
            [
                'name' => 'DANCELL BOGO',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. KARTINI KAYEN LOR, KEC PLEMAHAN - KEDIRI',
                'phone' => '082228814700',
                'whatsapp' => '082228814700',
                'google_maps_url' => 'https://maps.google.com/?cid=783928502904558182&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 10,
            ],
            [
                'name' => 'DANCELL CARUBAN',
                'city' => 'Madiun',
                'area' => 'KRAJAN MEJAYAN',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL A YANI NO. 62 KELURAHAN KRAJAN MEJAYAN (DEPAN POLSEK MEJAYAN)',
                'phone' => '081357712733',
                'whatsapp' => '081357712733',
                'google_maps_url' => 'https://maps.google.com/?cid=6213329453250568457&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 11,
            ],
            [
                'name' => 'DANCELL DLOPO',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. JOYOBOYO NO. 26 KARANGREJO (SELATAN RS AURA SYIFA 100M)',
                'phone' => '081328559494',
                'whatsapp' => '081328559494',
                'google_maps_url' => 'https://maps.google.com/?cid=13728518508963211572&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 12,
            ],
            [
                'name' => 'DANCELL KEPUNG',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL HARIJING KEPUNG-KEDIRI, TIMUR SWALAYAN ZAHRA KEPUNG',
                'phone' => '082137909988',
                'whatsapp' => '082137909988',
                'google_maps_url' => 'https://maps.google.com/?cid=2536777692871874282&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 13,
            ],
            [
                'name' => 'DANCELL MOJOROTO',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. K. H. AHMAD DAHLAN NO. 104 MOJOROTO-KEDIRI - SELATAN EX WARUNG GUNUNG',
                'phone' => '082312158989',
                'whatsapp' => '082312158989',
                'google_maps_url' => 'https://maps.google.com/?cid=3379388191210276081&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 14,
            ],
            [
                'name' => 'DANCELL PLOSO JOMBANG',
                'city' => 'Nganjuk',
                'area' => 'PLOSO',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. RAYA PLOSO-BABAT NO. 105, REJOMULYO, LOSARI, KEC. PLOSO, KABUPATEN JOMBANG (DEPAN TSAMANIA PLOSO JOMBANG)',
                'phone' => '081326989988',
                'whatsapp' => '081326989988',
                'google_maps_url' => 'https://maps.google.com/?cid=4715895777270456092&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 15,
            ],
            [
                'name' => 'DANCELL WATES',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. RAYA TAWANG WATES NO. 73A (50M SELATAN BCA WATES)',
                'phone' => '082311748989',
                'whatsapp' => '082311748989',
                'google_maps_url' => 'https://maps.google.com/?cid=390344564860484773&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 16,
            ],
            [
                'name' => 'DANCELL GURAH',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. Dr. WAHIDIN NO. 240 GURAH-KEDIRI',
                'phone' => '08132535512',
                'whatsapp' => '08132535512',
                'google_maps_url' => 'https://maps.google.com/?cid=16783184779798838488&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 17,
            ],
            [
                'name' => 'DANCELL KERTOSONO 2',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. A. YANI RT 4 RW 7 KUTOREJO, DEPAN BANK BNI CABANG KERTOSONO',
                'phone' => '082250258887',
                'whatsapp' => '082250258887',
                'google_maps_url' => 'https://maps.google.com/?cid=3469320903639052&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 18,
            ],
            [
                'name' => 'DANCELL PESANTREN',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => NULL,
                'is_hq' => false,
                'address' => 'JL. BRIGJEN POL. IBH PRANOTO NO. 85 KEDIRI',
                'phone' => '082118738989',
                'whatsapp' => '082118738989',
                'google_maps_url' => 'https://maps.google.com/?cid=14074182646978328268&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 19,
            ],
            [
                'name' => 'DANCELL GONDANG',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => '2021',
                'is_hq' => false,
                'address' => 'JL. PAHLAWAN N0. 13, GONDANG KULON, GONDANG - DEPAN PASAR GONDANG',
                'phone' => '082326143434',
                'whatsapp' => '082326143434',
                'google_maps_url' => 'https://maps.google.com/?cid=1710600459767402274&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 20,
            ],
            [
                'name' => 'DANCELL BERBEK',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => '2021',
                'is_hq' => false,
                'address' => 'JL. MAYJEND SUPENO N0. 49-117, BERBEK NGANJUK - DEPAN PASAR BERBEK',
                'phone' => '082394409991',
                'whatsapp' => '082394409991',
                'google_maps_url' => 'https://maps.google.com/?cid=7593131246935079300&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 21,
            ],
            [
                'name' => 'DANCELL SAMBI',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => '2021',
                'is_hq' => false,
                'address' => 'JL. KANDAT - KEDIRI, RINGINREJO KEC RINGINREJO - DEPAN PASAR SAMBI',
                'phone' => '082232619988',
                'whatsapp' => '082232619988',
                'google_maps_url' => 'https://maps.google.com/?cid=5872809517351749172&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 22,
            ],
            [
                'name' => 'DANCELL PETERONGAN',
                'city' => 'Jombang',
                'area' => 'Jombang',
                'year' => '2021',
                'is_hq' => false,
                'address' => 'JL. KOLONEL H. ISMAIL 70-50, MANCARMALANG - UTARA PASAR PETERONGAN',
                'phone' => '082124839998',
                'whatsapp' => '082124839998',
                'google_maps_url' => 'https://maps.google.com/?cid=2751623974508397080&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 23,
            ],
            [
                'name' => 'DANCELL KANDANGAN',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => '2021',
                'is_hq' => false,
                'address' => 'JL. JOMBANG NO. 80, KEBONDALEM, KANDANGAN - KEDIRI (UTARA PASAR KANDANGAN)',
                'phone' => '081233489995',
                'whatsapp' => '081233489995',
                'google_maps_url' => 'https://maps.google.com/?cid=8255670929619659327&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 24,
            ],
            [
                'name' => 'DANCELL SRENGAT',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => '2021',
                'is_hq' => false,
                'address' => 'JL. RAYA KEDIRI-BLITAR 24-17, SRENGAT II, SRENGAT BLITAR (DEPAN INDOMARET SRENGAT)',
                'phone' => '081357712893',
                'whatsapp' => '081357712893',
                'google_maps_url' => 'https://maps.google.com/?cid=3023490486645334754&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 25,
            ],
            [
                'name' => 'DANCELL MOJOAGUNG',
                'city' => 'Kediri',
                'area' => 'Kediri',
                'year' => '2022',
                'is_hq' => false,
                'address' => 'JL. SAYYID SULAIMAN 55-73, DSN. MUNCILAN, MOJOAGUNG-JOMBANG (UTARA BALAI DESA MANCILAN 150M)',
                'phone' => '081249218889',
                'whatsapp' => '081249218889',
                'google_maps_url' => 'https://maps.google.com/?cid=13772846753269602278&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 26,
            ],
            [
                'name' => 'DANCELL GRINGGING',
                'city' => 'Nganjuk',
                'area' => 'GROGOL',
                'year' => '2022',
                'is_hq' => false,
                'address' => 'JL. RAYA KEDIRI-NGANJUK NO. 11, SANTREN KIDUL, KEC. GROGOL, KAB. KEDIRI (BARAT PASAR GRINGGING)',
                'phone' => '081249218988',
                'whatsapp' => '081249218988',
                'google_maps_url' => 'https://maps.google.com/?cid=12772083763773023177&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 27,
            ],
            [
                'name' => 'DANCELL NGUNUT',
                'city' => 'Tulungagung',
                'area' => 'NGUNUT',
                'year' => '2022',
                'is_hq' => false,
                'address' => 'JL. RAYA NGUNUT II NO.78, LINGKUNGAN 5, NGUNUT, KEC. NGUNUT, KABUPATEN TULUNGAGUNG (UTARA BRI NGUNUT)',
                'phone' => '082234089988',
                'whatsapp' => '082234089988',
                'google_maps_url' => 'https://maps.google.com/?cid=2464960494202748675&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 28,
            ],
            [
                'name' => 'DANCELL NGORO (JOMBANG)',
                'city' => 'Jombang',
                'area' => 'NGORO',
                'year' => '2022',
                'is_hq' => false,
                'address' => 'JL. SUPRIADI, PANDEAN, NGORO, KEC. NGORO, JOMBANG (UTARA PASAR NGORO)',
                'phone' => '081249218989',
                'whatsapp' => '081249218989',
                'google_maps_url' => 'https://maps.google.com/?cid=13186300860211259835&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 29,
            ],
            [
                'name' => 'DANCELL BANDUNG (T AGUNG)',
                'city' => 'Tulungagung',
                'area' => 'Tulungagung',
                'year' => '2022',
                'is_hq' => false,
                'address' => 'JL. RAYA DURENAN - BANDUNG 24, GENENGAN, BANDUNG, KAB. TULUNGAGUNG (SELATAN RS MUHAMMADIYAH)',
                'phone' => '081359734889',
                'whatsapp' => '081359734889',
                'google_maps_url' => 'https://maps.google.com/?cid=16692976965262319898&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 30,
            ],
            [
                'name' => 'DANCELL TULUNGAGUNG KOTA',
                'city' => 'Tulungagung',
                'area' => 'TULUNGAGUNG',
                'year' => '2022',
                'is_hq' => false,
                'address' => 'JL. BASUKI RAHMAT NO. 62 KAMPUNGDALEM KEC. TULUNGAGUNG (DEPAN TOKO EMAS MAPAN BASRONI)',
                'phone' => '081334499880',
                'whatsapp' => '081334499880',
                'google_maps_url' => 'https://maps.google.com/?cid=10054515849442261729&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 31,
            ],
            [
                'name' => 'DANCELL MADIUN KOTA',
                'city' => 'Madiun',
                'area' => 'Madiun',
                'year' => '2022',
                'is_hq' => false,
                'address' => 'JL. KOLONEL MARHADI NO.67, PANGONGANGAN, MANGUNHARJO, KOTA MADIUN (BARAT ALUN-ALUN MADIUN)',
                'phone' => '081336529988',
                'whatsapp' => '081336529988',
                'google_maps_url' => NULL,
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 32,
            ],
            [
                'name' => 'DANCELL BLITAR KOTA',
                'city' => 'Blitar',
                'area' => 'KEPANJEN KIDUL',
                'year' => '2022',
                'is_hq' => false,
                'address' => 'JL. MASTRIP 5-13, KEPANJEN KIDUL, KEC. KEPANJEN KIDUL, KOTA BLITAR (BARAT LAMPU MERAH JEMBATAN MASTRIP)',
                'phone' => '081391779898',
                'whatsapp' => '081391779898',
                'google_maps_url' => 'https://maps.google.com/?cid=9437360852499219572&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 33,
            ],
            [
                'name' => 'DANCELL MAGETAN',
                'city' => 'Magetan',
                'area' => 'MAGETAN',
                'year' => '2022',
                'is_hq' => false,
                'address' => 'JL. JEND. SUDIRMAN NO.12, TAMBRAN, KEC. MAGETAN, KAB. MAGETAN (BARAT DEALER HONDA CEMARA AGUNG)',
                'phone' => '082229088819',
                'whatsapp' => '082229088819',
                'google_maps_url' => 'https://maps.google.com/?cid=13976608886598022399&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 34,
            ],
            [
                'name' => 'DANCELL REJOSO',
                'city' => 'Nganjuk',
                'area' => 'TALANG REJOSO',
                'year' => '2023',
                'is_hq' => false,
                'address' => 'JL. RAYA BOJONEGORO NO. 23 DESA TALANG REJOSO (DEPAN KORAMIL REJOSO)',
                'phone' => '081228428899',
                'whatsapp' => '081228428899',
                'google_maps_url' => 'https://maps.google.com/?cid=6995273628468295903&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 35,
            ],
            [
                'name' => 'DANCELL SOOKO',
                'city' => 'Kediri',
                'area' => 'PURI',
                'year' => '2023',
                'is_hq' => false,
                'address' => 'JL. WIJAYA KUSUMA NO. 21-22, GEDANG KLUTK, BANJARAGUNG, KEC. PURI, KAB. MOJOKERTO (DEPAN PASAR TANI BANJARAGUNG)',
                'phone' => '082125179988',
                'whatsapp' => '082125179988',
                'google_maps_url' => NULL,
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 36,
            ],
            [
                'name' => 'DANCELL LODOYO',
                'city' => 'Blitar',
                'area' => 'Blitar',
                'year' => '2023',
                'is_hq' => false,
                'address' => 'JL. RAYA BARAT NO.52, WONOREJO, KALIPANG, KEC. SUTOJAYAN KAB. BLITAR (TIMUR PASAR LODOYO)',
                'phone' => '082125119998',
                'whatsapp' => '082125119998',
                'google_maps_url' => 'https://maps.google.com/?cid=16773151501691839768&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 37,
            ],
            [
                'name' => 'DANCELL KEREP',
                'city' => 'Nganjuk',
                'area' => 'BAGOR',
                'year' => '2023',
                'is_hq' => false,
                'address' => 'JL. TAMANAN RT.4 RW.2, JIPANGAN, KUTOREJO, KEC. BAGOR, KAB. NGANJUK (UTARA PASAR KEREP)',
                'phone' => '082229500988',
                'whatsapp' => '082229500988',
                'google_maps_url' => NULL,
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 38,
            ],
            [
                'name' => 'DANCELL MOJO',
                'city' => 'Kediri',
                'area' => 'MOJO',
                'year' => '2023',
                'is_hq' => false,
                'address' => 'JL. MLATI, KEC. MOJO, KAB. KEDIRI (DEPAN GEPREK SAI MOJO KEDIRI)',
                'phone' => '081233489991',
                'whatsapp' => '081233489991',
                'google_maps_url' => 'https://maps.google.com/?cid=5896435833116063102&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 39,
            ],
            [
                'name' => 'DANCELL DLANGGU',
                'city' => 'Kediri',
                'area' => 'DLANGGU',
                'year' => '2023',
                'is_hq' => false,
                'address' => 'JL. RAYA DLANGGU NO.52, KASIA, POHKECIK, KEC. DLANGGU, KAB. MOJOKERTO (SELATAN BNI DLANGGU 60M)',
                'phone' => '082116598899',
                'whatsapp' => '082116598899',
                'google_maps_url' => NULL,
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 40,
            ],
            [
                'name' => 'DANCELL SEMEN',
                'city' => 'Kediri',
                'area' => 'SEMEN',
                'year' => '2023',
                'is_hq' => false,
                'address' => 'JL. ARGOWILIS KEC. SEMEN, KAB. KEDIRI (DEPAN BANK BRI SEMEN)',
                'phone' => '082137189898',
                'whatsapp' => '082137189898',
                'google_maps_url' => 'https://maps.google.com/?cid=8225642157859750592&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 41,
            ],
            [
                'name' => 'DANCELL BARAT',
                'city' => 'Magetan',
                'area' => 'BARAT',
                'year' => '2024',
                'is_hq' => false,
                'address' => 'JL. RAYA TEBON, SETRO, TEBON, KEC. BARAT, KAB. MAGETAN (BARAT HONDA AHASS TEBON)',
                'phone' => '082132389898',
                'whatsapp' => '082132389898',
                'google_maps_url' => 'https://maps.google.com/?cid=18061103564057273675&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 42,
            ],
            [
                'name' => 'DANCELL BANDAR',
                'city' => 'Kediri',
                'area' => 'MOJOROTO',
                'year' => '2024',
                'is_hq' => false,
                'address' => 'JL. KH. WACHID HASYIM NO. 158, BANDAR LOR, KEC. MOJOROTO, KEDIRI (SELATAN BELIKOPI BANDAR)',
                'phone' => '082141869988',
                'whatsapp' => '082141869988',
                'google_maps_url' => NULL,
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 43,
            ],
            [
                'name' => 'DANCELL GUDO',
                'city' => 'Jombang',
                'area' => 'Jombang',
                'year' => '2024',
                'is_hq' => false,
                'address' => 'JL. RAYA WANGKA, GUDO, JOMBANG (DEPAN PASAR GUDO)',
                'phone' => '082143789988',
                'whatsapp' => '082143789988',
                'google_maps_url' => 'https://maps.google.com/?cid=4224655767513063842&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 44,
            ],
            [
                'name' => 'DANCELL KANIGORO',
                'city' => 'Blitar',
                'area' => 'Blitar',
                'year' => '2024',
                'is_hq' => false,
                'address' => 'JL. MANUKWARI, RT 06/RW 04, JAJAR, SATREYAN, KANIGORO, BLITAR (UTARA BANK MANDIRI KANIGORO)',
                'phone' => '085210878899',
                'whatsapp' => '085210878899',
                'google_maps_url' => 'https://maps.google.com/?cid=5750311814452090107&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 45,
            ],
            [
                'name' => 'DANCELL UTERAN',
                'city' => 'Madiun',
                'area' => 'GEGER',
                'year' => '2024',
                'is_hq' => false,
                'address' => 'JL. RAYA PONOROGO, GULINGAN, UTERAN, KEC. GEGER, KAB. MADIUN (DEPAN ATM BNI46 24 JAM PAGOTAN)',
                'phone' => '082311678899',
                'whatsapp' => '082311678899',
                'google_maps_url' => 'https://maps.google.com/?cid=14944092084268103627&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 46,
            ],
            [
                'name' => 'DANCELL PANJER TULUNGAGUNG',
                'city' => 'Tulungagung',
                'area' => 'Tulungagung',
                'year' => '2024',
                'is_hq' => false,
                'address' => 'JL. RAYA DEMUK-KALANGAN, PANJEREJO, REJOTANGAN, TULUNGAGUNG (DEPAN PASAR PANJEREJO REJOTANGAN)',
                'phone' => '082333828899',
                'whatsapp' => '082333828899',
                'google_maps_url' => 'https://maps.google.com/?cid=7490160635092733483&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 47,
            ],
            [
                'name' => 'DANCELL POHJEJER',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => '2024',
                'is_hq' => false,
                'address' => 'JL. RAYA POHJEJER NO.11, POHJEJER, GONDANG, MOJOKERTO (500 METER TIMUR PASAR POHJEJER)',
                'phone' => '082333828898',
                'whatsapp' => '082333828898',
                'google_maps_url' => 'https://maps.google.com/?cid=6833743285806513521&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 48,
            ],
            [
                'name' => 'DANCELL TRENGGALEK KOTA',
                'city' => 'Trenggalek',
                'area' => 'TRENGGALEK',
                'year' => '2024',
                'is_hq' => false,
                'address' => 'JL. PANGLIMA SUDIRMAN NO. 146, NGROWO, NGANTRU, KEC. TRENGGALEK, KAB. TRENGGALEK (SELATAN BANK JATIM NGANTRU TRENGGALEK)',
                'phone' => '085222039898',
                'whatsapp' => '085222039898',
                'google_maps_url' => 'https://maps.google.com/?cid=10362336493040599013&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 49,
            ],
            [
                'name' => 'DANCELL GANDUSARI TRENGGALEK',
                'city' => 'Trenggalek',
                'area' => 'GANDUSARI',
                'year' => '2024',
                'is_hq' => false,
                'address' => 'JL. RAYA GANDUSARI - KAMPAK, TUGU, SUKOREJO, KEC. GANDUSARI, KAB. TRENGGALEK 66372 (50 METER UTARA BANK MANDIRI TRENGGALEK GANDUSARI)',
                'phone' => '081324569988',
                'whatsapp' => '081324569988',
                'google_maps_url' => 'https://maps.google.com/?cid=11154532292375412319&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 50,
            ],
            [
                'name' => 'DANCELL MOJOSARI MOJOKERTO',
                'city' => 'Kediri',
                'area' => 'MOJOSARI',
                'year' => '2025',
                'is_hq' => false,
                'address' => 'JL. NIAGA, RE III, SARIREJO, KECAMATAN MOJOSARI, KABUPATEN MOJOKERTO, JAWA TIMUR 61382 (SELATAN PDS SARIREJO SAMPING DOKTER GIGI PAK RUDI)',
                'phone' => '082227259998',
                'whatsapp' => '082227259998',
                'google_maps_url' => 'https://maps.app.goo.gl/Gn6VXJwjovLYSimb6',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 51,
            ],
            [
                'name' => 'DANCELL JOGOROGO NGAWI',
                'city' => 'Ngawi',
                'area' => 'JOGOROGO',
                'year' => '2025',
                'is_hq' => false,
                'address' => 'JL. MAJAPAHIT, RT.03/RW. 02, DUKUH SAMBUNGAN, KECAMATAN JOGOROGO, KABUPATEN NGAWI, JAWA TIMUR 63262 (UTARA KORWIL DISPENDIK, DEPAN MOMOYO)',
                'phone' => '082146308889',
                'whatsapp' => '082146308889',
                'google_maps_url' => 'https://maps.google.com/?cid=1292355377218583445&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 52,
            ],
            [
                'name' => 'DANCELL BLITAR 2',
                'city' => 'Nganjuk',
                'area' => 'Nganjuk',
                'year' => '2025',
                'is_hq' => false,
                'address' => 'JL. VETERAN PLOSOKEREP, SANANWETAN, KOTA BLITAR, JAWA TIMUR (BUNDERAN VETERAN KE UTARA 150M, TIMUR JALAN)',
                'phone' => '082221938899',
                'whatsapp' => '082221938899',
                'google_maps_url' => 'https://maps.google.com/?cid=3848807467114628180&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 53,
            ],
            [
                'name' => 'DANCELL PONOROGO',
                'city' => 'Ponorogo',
                'area' => 'PONOROGO',
                'year' => '2025',
                'is_hq' => false,
                'address' => 'JL. SULTAN AGUNG, SULTAN AGUNG, NOLOGATEN, KEC. PONOROGO, KABUPATEN PONOROGO (100M SELATAN MASJID NU TIMUR JALAN)',
                'phone' => '082221988809',
                'whatsapp' => '082221988809',
                'google_maps_url' => 'https://maps.google.com/?cid=10114796385724027450&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQ',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 54,
            ],
            [
                'name' => 'DANCELL DOLOPO',
                'city' => 'Madiun',
                'area' => 'DOLOPO',
                'year' => '2025',
                'is_hq' => false,
                'address' => 'JL. ADIL MAKMUR, KRAJAN, BANGUNSARI, KEC. DOLOPO, KABUPATEN MADIUN (100M BARAT PASAR DOLOPO)',
                'phone' => '082229089898',
                'whatsapp' => '082229089898',
                'google_maps_url' => 'https://maps.app.goo.gl/HDydP8LvnqruFuWT7',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 55,
            ],
            [
                'name' => 'DANCELL SUKODONO',
                'city' => 'Sidoarjo',
                'area' => 'SUKODONO',
                'year' => '2026',
                'is_hq' => false,
                'address' => 'JL. RAYA SAIMBANG, BOGEM, KEBONAGUNG, KEC. SUKODONO (150 METER SELATAN KANTOR DESA KEBONAGUNG)',
                'phone' => '081233489997',
                'whatsapp' => '081233489997',
                'google_maps_url' => 'https://maps.app.goo.gl/azw3EnbSZHxzEaWy5',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 56,
            ],
            [
                'name' => 'DANCELL BABAT',
                'city' => 'Jombang',
                'area' => 'Jombang',
                'year' => '2026',
                'is_hq' => false,
                'address' => 'JL. RAYA BABAT-JOMBANG NO 78, SANTREN, BANARAN, KEC BABAT, KABUPATEN LAMONGAN (50 METER SELATAN MASJID AR ROUDLOH)',
                'phone' => '08212189898',
                'whatsapp' => '08212189898',
                'google_maps_url' => 'https://maps.app.goo.gl/x8bH8f5sYgZJWgLX9',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 57,
            ],
            [
                'name' => 'DANCELL WEDORO',
                'city' => 'Sidoarjo',
                'area' => 'WARU',
                'year' => '2026',
                'is_hq' => false,
                'address' => 'JL. BRIGJEN KATAMSO, NO 17 WEDORO, KEC. WARU, KABUPATEN SIDOARJO (200 METER PEGADAIAN UPC REWWIN)',
                'phone' => '08132533088',
                'whatsapp' => '08132533088',
                'google_maps_url' => 'https://maps.app.goo.gl/e1qUkEs5pmPUH91N6',
                'opening_hours' => 'Buka Setiap Hari (08.00 - 21.00 WIB)',
                'is_active' => true,
                'order' => 58,
            ],
        ];

        foreach ($branches as $data) {
            $data['slug'] = Str::slug($data['name']);
            Branch::create($data);
        }
    }
}
